org = 'growthbook'
primary_region = 'sjc'

[build]

[env]
  IS_CLOUD = true
  IS_MULTI_ORG = true
  ALLOW_SELF_ORG_CREATION = true
  DISABLE_TELEMETRY = "debug"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
