name: PR Preview Environment

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/**"
      - "!**.md"
      - "yarn.lock"
      - "Dockerfile"
      - ".dockerignore"
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  preview:
    if: ${{ github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: pr-${{ github.event.number }}
      cancel-in-progress: true
    environment:
      name: preview
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy PR preview
        id: deploy
        uses: superfly/fly-pr-review-apps@1.3.0
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        with:
          name: growthbook-pr-${{ github.event.number }}
          org: growthbook
          region: sjc
          secrets:
            APP_ORIGIN=https://growthbook-pr-${{ github.event.number }}.fly.dev
            API_HOST=https://growthbook-pr-${{ github.event.number }}.fly.dev:4433
            MONGODB_URI=${{ secrets.MONGODB_URI }}

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl ips allocate-v4 --shared -a growthbook-pr-${{ github.event.number }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
